namespace Services.Shared.Enums
{
    public enum Permissions
    {
        CreateBooking,
        DeleteBooking,
        UpdateBooking,
        GetBookingById,
        PaginateBookings,
        CreateCategory,
        DeleteCategory,
        UpdateCategory,
        PaginateCategories,
        CreateDiscount,
        DeleteDiscount,
        UpdateDiscount,
        GetDiscountById,
        PaginateDiscounts,
        CreateService,
        DeleteService,
        UpdateService,
        GetAllServices,
        GetService,
        PaginateService,
        CreateUser,
        DeleteUser,
        UpdateUser,
        GetUser,
        AssignWorkerToService,
        RemoveWorkerFromService,
        UpdateWorkerOnService,
        UpdateWorkerStatus,
        GetAllWorker,
        GetAllServicesWithWorkers,
        GetWorkerOnService,
        GetWorkersBasedOnStatus,
        GetWorkersOnService,
        GetWorkerPaginate

    }
}
